config/routes.rb
Scheduling::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
	resources :users do
		member do
			get :google
		end
	end
	
	resources :sessions, only: [:new, :create, :destroy]
	resources :features do
	  member do 
	    get :toggle
	  end
	end
	get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete
	
	resources :schedules do
		collection do
			get :calendar
			get :addnew
		end
		member do
			get :rewrite
			get :calendar_update
			get :pop_up
		end
	end
  resources :projects do
		collection do
			get :autocomplete
		end
	end
	resources :static_pages do
		member do
			get :rewrite
		end
	end
	root to: "static_pages#home"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :signed_in_user
  require 'will_paginate/array'
  def home
   	@project = Project.new
   	@start_date=Time.zone.now.beginning_of_week
   	@end_date=Time.zone.now.end_of_week
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home_buttons.html.erb
<% if project.active?(current_user)  %>
	<button class="btn btn-danger btn-lg home-left" name="stop" type="submit">
		<i class="glyphicon glyphicon-pause"></i>
	</button>
<% else %>
	<button class="btn btn-success btn-lg home-left" name="go_single" type="submit">
		<i class="glyphicon glyphicon-play"></i>
	</button>
<% end %>
<button class="btn btn-warning btn-lg home-left" name="del" type="submit">
	<i class="glyphicon glyphicon-star"></i>
</button>

app/views/static_pages/_project.html.erb
<% Project.all.sort_by(&:name).each do |project| %>
<% if project.features.where(user_id: current_user).first && project.features.where(user_id: current_user).first.featured %>
		<%= content_tag_for :div, project, class: "img-rounded" do %>
		<button class="btn btn-inverse title" data-toggle="modal" data-target="#modal<%= project.id %>" id="project_title<%= project.id %>"><%= project.name %></button>
		<%= form_tag(new_schedule_path, class: "form-inline", :style => "display:inline", method: :get, remote: true) do %>
		
		
		<br>
		<%= hidden_field_tag :name, project.name  %>
		<span id="btn<%= project.id %>"><%= render "static_pages/home_buttons", project: project %></span>
		<% end %>
<% end %>
    <%= render "static_pages/project_popup", project: project, start_date: start_date, end_date: end_date %>
	<% end %>
<% end %>

app/views/static_pages/_project_popup.html.erb
<div class="modal fade" id="modal<%= project.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel<%= project.id %>"><%= render 'projects/project_title_link', project: project %></h4>
        
        <div style='padding-left:11px'><a href="<%= edit_project_path(project) %>" data-remote="true"> <span class="glyphicon glyphicon-edit"></span> Edit Title</a> | <a href="<%= toggle_feature_path(project.features.where(user_id: current_user.id).first_or_create) %>">
<% if project.features.where(user_id: current_user.id).first_or_create.featured %>
<span class="glyphicon glyphicon-eye-open"></span> 
<% else %>
<span class="glyphicon glyphicon-eye-close"></span>
<% end %> Toggle Visibility
</a> | <a confirm="You sure?" data-method="delete" href="<%= project_path(project) %>" rel="nofollow" title="Delete <%= project.name %>"><span class="glyphicon glyphicon-remove"></span> Delete Project</a></div>
      </div>
      <div class="modal-body" style="text-align:center">
        Time Span:

<%= form_tag(project_path(project), class: 'form-inline', style: 'display:inline;margin-left:auto;margin-right:auto', method: :get, remote: true) do %>
	<%= text_field_tag 'start_date', start_date.strftime("%m/%d/%Y"), class: "form-control datepicker-no-time", id: "checkin#{project.id}", style: "display:inline;width:100px" %> - <%= text_field_tag 'end_date', end_date.strftime("%m/%d/%Y"), class: "form-control datepicker-no-time", id: "checkout#{project.id}", style: "display:inline;width:100px" %>
<%= submit_tag "Submit", class: 'btn btn-default' %>
      <% end %>
      
      
      <p>Total Time Spent during period = <span id="time_<%= project.id %>"><%= (project.time_spent(start_date,end_date,current_user)/60/60).ceil %></span> hours</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_stop_button.html.erb
<% if !Schedule.active_project(current_user).blank? %>
  <button class="btn btn-default" id="running" name="stop" type="submit">
    <i class="glyphicon glyphicon-pause"></i>
  </button>
<% end %>

app/views/static_pages/_total_time.html.erb
<p><%= Project.total_time.round(1) %> hours worked today</p>

app/views/static_pages/home.html.erb
<div id="project_boxes" data-count="<%= Feature.where(featured: true, user_id:current_user.id).count %>">
	<%= render "static_pages/project", start_date: @start_date, end_date: @end_date %>
</div>


<script>
$(function () {
  $("#project_<%= Project.active(current_user)? Project.active(current_user).id : 0 %>").addClass("project-primary");
 });
</script>