config/routes.rb
Scheduling::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
	resources :users do
		member do
			get :google
		end
	end
	
	resources :sessions, only: [:new, :create, :destroy]
	resources :features do
	  member do 
	    get :toggle
	  end
	end
	get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete
	
	resources :schedules do
		collection do
			get :calendar
			get :addnew
		end
		member do
			get :rewrite
			get :calendar_update
			get :pop_up
		end
	end
  resources :projects do
		collection do
			get :autocomplete
		end
	end
	resources :static_pages do
		member do
			get :rewrite
		end
	end
	root to: "static_pages#home"
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

  belongs_to :project
  accepts_nested_attributes_for :project
  belongs_to :user
  accepts_nested_attributes_for :user
  
  def happens_during?(start_date,end_date)
  	(start_date < start_at && start_at < end_date) || (start_date < end_at && end_at < end_date)
  end
  
  def project_name
  	project.try(:name)
  end
  
  def duration
  	(end_at ? end_at : 0.hours.ago)-start_at
  end
  
  def project_name=(name)
  	self.project = Project.where(name: name).first_or_create if name.present?
  end
  
  def self.total_time(span,user)
  	total_time = 0
  	if span == "day"
		begday = 0.minutes.ago.beginning_of_day
		endday = 0.minutes.ago.end_of_day
		elsif span == "week"
		begday = 0.minutes.ago.beginning_of_week(start_day = :sunday)
		endday = 0.minutes.ago.end_of_week(start_day = :sunday)
		end
		Schedule.all.where("user_id = ? AND ((start_at > ? AND start_at < ?) OR (end_at > ? AND end_at < ?))",1,begday,endday,begday,endday).each do |s|
			start = s.start_at
			finish = s.end_at.blank? ? 0.minutes.ago : s.end_at
			if  begday < finish && finish < endday && begday < start && start < endday
			elsif begday < finish && finish < endday
				start = begday
			elsif begday < start && start < endday
				finish = endday
			else
				start = begday
				finish = begday
			end
			total_time = total_time + (finish - start)
		end
		
		return total_time
  end
  
  
  
  def formatted_start_at
		start_at.strftime('%m/%d/%Y %I:%M %p')
	end
	
	def formatted_start_at=(time_str)
		self.start_at = Time.strptime("#{time_str} #{Time.zone.now.strftime('%Z')}", '%m/%d/%Y %I:%M %p')
	end
	
	def formatted_end_at
		end_at.strftime('%m/%d/%Y %I:%M %p')
	end
	
	def formatted_end_at=(time_str)
		self.end_at = Time.strptime("#{time_str} #{Time.zone.now.strftime('%Z')}", '%m/%d/%Y %I:%M %p')
	end
	
	def self.active_project(user)
  	if where(end_at: nil,user_id: user.id).first
  		where(end_at: nil,user_id: user.id).first.project
  	end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_filter :signed_in_user
  require 'will_paginate/array'
	
	def calendar_update
		day_delta = params[:day_delta].to_f
		minute_delta = params[:minute_delta].to_f
		@schedule = Schedule.find(params[:id])
		old_start_at = @schedule.start_at
		old_end_at = @schedule.end_at
		if params[:method] == "drop"
			new_start_at = old_start_at + day_delta.day + minute_delta.minute
		else
			new_start_at = old_start_at
		end
		new_end_at = old_end_at + day_delta.day + minute_delta.minute
		@schedule.update_attributes(start_at: new_start_at, end_at: new_end_at)

	end
	
	def new
	  @start_date=Time.zone.today.beginning_of_week
    @end_date=Time.zone.today.end_of_week
    if params[:go] || params[:go_single]
    	@project = Project.where(name: params[:name]).first_or_create
		  @project.save!
    	@command="go"
		 	current_project=Schedule.where(end_at: nil, user_id: current_user.id).first
		  if params[:now] == "true" || params[:go_single]
		  	if current_project
					current_project.update_attributes(end_at:Time.zone.now)
					@current_project=current_project.project
				else
				  @current_project=nil
				end
		  	Schedule.create!(project_id:@project.id,start_at:Time.zone.now,user_id:current_user.id)		  	
		  else
 		  	if current_project
					current_project.update_attributes(end_at:Time.strptime("#{params[:start_at]} #{Time.zone.now.strftime('%Z')}", '%m/%d/%Y %I:%M %p %Z'))
					@current_project=current_project.project
				else
				  @current_project=nil
				end
		  	Schedule.create!(project_id:@project.id,start_at:Time.strptime("#{params[:start_at]} #{Time.zone.now.strftime('%Z')}", '%m/%d/%Y %I:%M %p %Z'),user_id:current_user.id)
		 	end
		  featured=@project.features.where(user_id: current_user.id).first
		  if featured.blank?
		    featured=@project.features.where(user_id: current_user.id).first_or_create
        featured.update_attributes(featured:true)
         @new = true
		  elsif featured.featured
		    @new = false
		  else
		    featured=@project.features.where(user_id: current_user.id).first_or_create
        featured.update_attributes(featured:true)
		    @new = true
		  end
		  featured.save!
		elsif params[:del]
		  @project = Project.where(name: params[:name]).first
			@command="del"
			@new = false
			featured=@project.features.where(user_id: current_user.id).first_or_create
			featured.update_attributes(featured:false)
		else
			@command="stop"
			@new = false
			current_project=Schedule.where(end_at: nil, user_id: current_user.id).first
			if current_project
				current_project.update_attributes(end_at:Time.zone.now)
				@current_project=current_project.project
			end
		end

		respond_to do |format|
      format.html {redirect_to request.referer}
      format.js
    end
	end
	
	def index
		@title = "Edit Schedule"
		@per_page = params[:per_page].blank? ? 1 : params[:per_page]
		@schedules = Schedule.where(user_id: current_user.id).sort_by(&:id).reverse.paginate(:page => params[:page], :per_page => @per_page)
		respond_to do |format|
      format.html
      format.js
    end
	end
	
	def edit
		@schedule=Schedule.find(params[:id])
		@schedule.update_attributes(project_name: params[:project_name], start_at: Time.strptime("#{params[:start_at]} #{Time.zone.now.strftime('%Z')}", '%m/%d/%Y %I:%M %p %Z'), end_at: (!params[:end_at].blank? ? Time.strptime("#{params[:end_at]} #{Time.zone.now.strftime('%Z')}", '%m/%d/%Y %I:%M %p %Z') : nil))
		respond_to do |format|
      format.html {redirect_to request.referer}
    end
	end

	def pop_up
		@schedule=Schedule.find(params[:id])
	end
		
	def rewrite
		@schedule = Schedule.where(id: params[:id]).first
		@command = params[:commit]
		if @command == "go"
			@schedule.update_attributes(project_name: params[:project_name], start_at: Time.strptime("#{params[:start_at]} #{Time.zone.now.strftime('%Z')}", '%m/%d/%Y %I:%M %p %Z'), end_at: (!params[:end_at].blank? ? Time.strptime("#{params[:end_at]} #{Time.zone.now.strftime('%Z')}", '%m/%d/%Y %I:%M %p %Z') : nil))
			featured=@schedule.project.features.where(user_id: current_user.id).first_or_create
			featured.update_attributes(featured: true)
			@schedule.save!
		elsif @command == "del"
		  @schedule.destroy
		end
		respond_to do |format|
	    format.html {redirect_to schedules_path}
	    format.js
	  end
	end
	
	def addnew
		current_project=Schedule.where(end_at: nil, user_id: current_user.id).first
	  if current_project
	  	current_project.update_attributes(end_at:Time.zone.now)
	  	@current_schedule=current_project
	  else
	  	@current_schedule=nil
	  end
	  @schedule = Schedule.new(start_at:Time.zone.now,user_id:current_user.id)
	  @schedule.save!
	  respond_to do |format|
	    format.html {redirect_to schedules_path}
	    format.js
	  end
	end
	
	def destroy
    @schedule=Schedule.where(id: params[:id]).first
    @schedule.destroy
    
    respond_to do |format|
      format.html {redirect_to schedules_path}
      format.js
    end
  end
  def calendar
  	@title= "Calendar"
  end
  
end

app/views/schedules/_edit.html.erb
	<%= form_tag edit_schedule_path(schedule), method: "get", class: "form-horizontal" do %>

		<div class="form-group">
			<label for="<%= schedule.id %>" class="col-sm-4 control-label">Project</label>
			<div class="col-sm-8">
				<%= text_field_tag :project_name, (schedule.project.name if schedule.project), data: {autocomplete_source: autocomplete_projects_path}, class: "autocomplete form-control", id: schedule.id %>
			</div>
			</div>

		<div class="form-group">
			<label for="start_at<%= schedule.id %>" class="col-sm-4 control-label">Start Time</label>
			<div class="datetimepicker col-sm-8" data-date-format="MM/DD/YYYY hh:mm A">
	    <%= text_field_tag :start_at, (schedule.start_at.strftime('%m/%d/%Y %I:%M %p') if schedule.start_at), id: "start_at#{schedule.id}", class: "form-control"  %>
	  </div>
	  </div>
	  <div class="form-group">
			<label for="end_at<%= schedule.id %>" class="col-sm-4 control-label">End Time</label>
			<div class="datetimepicker col-sm-8" data-date-format="MM/DD/YYYY hh:mm A">
	    <%= text_field_tag :end_at, (schedule.end_at.strftime('%m/%d/%Y %I:%M %p') if schedule.end_at), id: "end_at#{schedule.id}", class: "form-control"  %>
	  </div>
	  </div>
		<div class="modal-footer">

			<%= submit_tag"Save changes", class: "btn btn-default" %>
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		</div>
	<% end %>

app/views/schedules/_schedule.html.erb
<%= content_tag_for :div, schedule, class: "img-polaroid schedule_time" do %>
  <%= form_tag rewrite_schedule_path(schedule), method: :get, name: "form#{schedule.id}", remote: true do %>
    <%= text_field_tag :project_name, (schedule.project.name if schedule.project), data: {autocomplete_source: autocomplete_projects_path}, class: "autocomplete", id: schedule.id %><br>
    <div class="datetimepicker" data-date-format="MM/DD/YYYY hh:mm A">
	    <%= text_field_tag :start_at, (schedule.start_at.strftime('%m/%d/%Y %I:%M %p') if schedule.start_at), id: "start_at#{schedule.id}" %><br>
	  </div>
	  <div class="datetimepicker" data-date-format="MM/DD/YYYY hh:mm A">
	    <%= text_field_tag :end_at, (schedule.end_at.strftime('%m/%d/%Y %I:%M %p') if schedule.end_at), id: "end_at#{schedule.id}"  %><br>
	  </div>
	  <div style="float:right">
		  <%= hidden_field_tag :commit %>
	    <span id="update_<%= schedule.id %>" class="thumb">
		    <i class="glyphicon glyphicon-thumbs-up"></i>
		  </span>
		  <button class="btn btn-success btn-large" name="go" type="submit" onClick="document.form<%= schedule.id %>.commit.value='go'">
    		<i class="glyphicon glyphicon-retweet"></i>
    	</button>
    	<button class="btn btn-danger btn-large" name="del" type="submit" onClick="document.form<%= schedule.id %>.commit.value='del'">
			  <i class="glyphicon glyphicon-remove"></i>
		  </button>
	  </div>	
  <% end %>
<% end %>

app/views/schedules/addnew.js.erb
$("#hours_popup").data('day',<%= Schedule.total_time('day',current_user) %>)
$("#hours_popup").data('week',<%= Schedule.total_time('week',current_user) %>)
$("#hours_popup").data('working', <%= current_user.working? %>)
schedTimer1()
<% if !@current_schedule.blank? %>
	$('#end_at<%= @current_schedule.id %>').val('<%= @current_schedule.formatted_end_at %>')
<% end %>
$('#schedules').prepend($('<%=j render @schedule %>').fadeIn("slow"))
$("#stopbutton").html("<%=j render 'static_pages/stop_button' %>")
$( ".autocomplete" ).autocomplete({source: $( ".autocomplete:first" ).data('autocomplete-source')})
$(".datetimepicker").datetimepicker({sideBySide: true})

app/views/schedules/calendar.html.erb
<div id='calendar'></div>
<% colors= ['#ff0000','#00ff00','#0000ff','#7cb5ec', '#434348', '#90ed7d', '#f7a35c', '#8085e9', '#f15c80', '#e4d354', '#8085e8', '#8d4653', '#91e8e1'] %>
<% repcol=(Project.all.sort_by(&:id).last.id.to_f/colors.length).ceil %>
<% colors = colors * repcol %>
<script>
$(function() {
  $('#calendar').fullCalendar({
    height: 600,
    theme: false,
    firstHour: 8,
    allDaySlot: false,
    defaultView: 'agendaWeek',
		slotMinutes: 30,
    snapMinutes: 5,
    editable: true,
		selectable: true,
    header: {
			left: 'prev,next today',
			center: 'title',
			right: 'month,agendaWeek,agendaDay'
		},
		eventClick: function(event, jsEvent, view) {
			$.ajax({
				type:"GET",
				url: "/schedules/" + event.id + "/pop_up.js"
			});
    },
		eventResize: function(event,dayDelta,minuteDelta,allDay,revertFunc) {
			$.ajax({
				type:"GET",
				url: "/schedules/" + event.id + "/calendar_update/",
				data: "minute_delta="+minuteDelta+"&day_delta="+dayDelta+"&method=resize"
			});
		},
		eventDrop: function(event,dayDelta,minuteDelta,allDay,revertFunc) {
			$.ajax({
				type:"GET",
				url: "/schedules/" + event.id + "/calendar_update/",
				data: "minute_delta="+minuteDelta+"&day_delta="+dayDelta+"&method=drop"
			});
		},
		events: [
		<% Schedule.where(user_id: current_user.id).sort_by(&:id).each do |event| %>
			<% if event.duration > 60 && !event.project.blank? %>
			{
				title: '<%= event.project.name %>',
				id: '<%= event.id %>',
				selectable: true,
				color: '<%= colors[event.project_id] %>',

				start: new Date(<%= event.start_at.year %>, <%= event.start_at.month-1 %>, <%= event.start_at.day %>, <%= event.start_at.hour %>, <%= event.start_at.min %>),
				<% if event.end_at %>
					end: new Date(<%= event.end_at.year %>, <%= event.end_at.month-1 %>, <%= event.end_at.day %>, <%= event.end_at.hour %>, <%= event.end_at.min %>),
				<% else %>
					end: new Date(<%= 0.hours.ago.year %>, <%= 0.hours.ago.month-1 %>, <%= 0.hours.ago.day %>, <%= 0.hours.ago.hour %>, <%= 0.hours.ago.min %>),
				<% end %>
				allDay: false
			}<%= "," if event != Schedule.last %>
			<% end %>
		<% end %>
		]})
    	if ($(window).width() < 575) {
		      $('#calendar').fullCalendar('changeView', 'agendaDay');
		    } else {
		      $('#calendar').fullCalendar('changeView', 'agendaWeek');
		    }
});

</script>




<div class="modal fade" id="Schedule" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="SettingsLabel">Update Project</h4></div>
        <div class="modal-body modal-body-cal" style="text-align:center">
		</div>
    </div>
  </div>
</div>

app/views/schedules/destroy.js.erb
$("#hours_popup").data('day',<%= Schedule.total_time("day",current_user) %>)
$("#hours_popup").data('week',<%= Schedule.total_time("week",current_user) %>)
$("#hours_popup").data('working',<%= current_user.working? %>)
schedTimer1()
$( ".autocomplete" ).autocomplete({source: $( ".autocomplete:first" ).data('autocomplete-source')})
$(".datetimepicker").datetimepicker({sideBySide: true})
$("#schedule_<%= @schedule.id %>").fadeOut("slow")

app/views/schedules/index.html.erb
<div id="projects" data-update-url="<%= schedules_path %>">
<div style="margin-left:auto;margin-right:auto" id="paginate"><%= will_paginate @schedules, renderer: BootstrapPagination::Rails, class: 'pagination pagination-sm' %></div>
  <div>
    <%= link_to addnew_schedules_path, remote: true do %>
      <div class="addnew img-rounded img-polaroid schedule_time">
        <div>
          <i class="glyphicon glyphicon-plus-sign" style="font-size:3em"></i><br>

          Do something else...<br>
        </div>
      </div>
    <% end %>
    <div id="schedules">
      <%= render @schedules %>
    </div>
  </div>
</div>

	
	

app/views/schedules/index.js.erb
$("#schedules").html('<%=j render @schedules %>')
$("#paginate").html('<%=j will_paginate @schedules, renderer: BootstrapPagination::Rails, class: 'pagination pagination-sm' %>')
$(".autocomplete").autocomplete({source: $(".autocomplete:first").data('autocomplete-source')})
$(".datetimepicker").datetimepicker({sideBySide: true})

app/views/schedules/new.js.erb
<% if @command== "del" %> 
$("#project_<%= @project.id %>").fadeOut("slow")
<% elsif @command == "go" %> 
<% if @new %>
	$("#project_boxes").html("<%=j render 'static_pages/project', start_date: @start_date, end_date: @end_date %>")
	$("#project_<%= @project.id %>").addClass("project-primary")
<% else %>
	<% if @current_project %>
	$(".project-primary span").html("<%=j render 'static_pages/home_buttons', project: @current_project %>")
	$(".project-primary").removeClass("project-primary")
	<% end %>
	$("#project_<%= @project.id %>").addClass("project-primary")
	$(".project-primary #btn<%= @project.id %>").html("<%=j render 'static_pages/home_buttons', project: @project %>")
<% end %>
<% elsif @command == "stop" %>
$(".project-primary span").html("<%=j render 'static_pages/home_buttons', project: @current_project %>")
$(".project-primary").removeClass("project-primary")
<% end %>
$("#hours_popup").data('day',<%= Schedule.total_time('day',current_user) %>)
$("#hours_popup").data('week',<%= Schedule.total_time('week',current_user) %>)
$("#hours_popup").data('working',<%= current_user.working? %>)
schedTimer()
$("#stopbutton").html("<%=j render 'static_pages/stop_button' %>")
$("#name").val("")

app/views/schedules/pop_up.js.erb
$('.modal-body-cal').html('<%=j render "edit", schedule: @schedule %>');
$('#Schedule').modal('show');
$(".datetimepicker").datetimepicker({sideBySide: true});
$(".autocomplete").autocomplete({source: $( ".autocomplete" ).data('autocomplete-source')});

app/views/schedules/rewrite.js.erb
$("#hours_popup").data('day',<%= Schedule.total_time("day",current_user) %>)
$("#hours_popup").data('week',<%= Schedule.total_time("week",current_user) %>)
$("#hours_popup").data('working',<%= current_user.working? %>)
$( ".autocomplete" ).autocomplete({source: $( ".autocomplete:first" ).data('autocomplete-source')})
$(".datetimepicker").datetimepicker({sideBySide: true})
$("#stopbutton").html("<%=j render 'static_pages/stop_button' %>")
schedTimer1()
<% if @command == "go" %>
$("#update_<%= @schedule.id %>").fadeIn("slow").fadeOut("slow")
<% else %>
$("#schedule_<%= @schedule.id %>").fadeOut("slow")
<% end %>

app/views/schedules/show.js.erb
$("#schedules").html('<%=j render @schedules %>')
$("#paginate").html('<%=j will_paginate @schedules, renderer: BootstrapPagination::Rails, class: 'pagination pagination-sm' %>')

app/views/schedules/update.js.erb
$("#update_<%= @schedule.id %>").text("Updated!").fadeIn("slow").fadeOut("slow")