config/routes.rb
Scheduling::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
	resources :users do
		member do
			get :google
		end
	end
	
	resources :sessions, only: [:new, :create, :destroy]
	resources :features do
	  member do 
	    get :toggle
	  end
	end
	get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete
	
	resources :schedules do
		collection do
			get :calendar
			get :addnew
		end
		member do
			get :rewrite
			get :calendar_update
			get :pop_up
		end
	end
  resources :projects do
		collection do
			get :autocomplete
		end
	end
	resources :static_pages do
		member do
			get :rewrite
		end
	end
	root to: "static_pages#home"
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_span_form.html.erb
<div style="margin-bottom:10px;">
Time Span:

<%= form_tag(user_path(user), class: 'form-inline', style: 'display:inline;', method: :get) do %>
	<%= text_field_tag 'start_date', start_date.strftime("%m/%d/%Y"), class: "form-control datepicker-no-time", style: "width:100px;display:inline;" %> - <%= text_field_tag 'end_date', end_date.strftime("%m/%d/%Y"), class: "form-control datepicker-no-time", style: "width:100px;display:inline;" %>
<%= submit_tag "Submit", class: 'btn btn-default', style: "display:inline;" %>
<%= link_to 'Last Week',user_path(@user, start_date: (Date.today.beginning_of_week(start_day = :sunday)-7).strftime("%m/%d/%Y"),end_date: (Date.today.end_of_week(start_day = :sunday)-7).strftime("%m/%d/%Y")), class: 'btn btn-default' %>
<% link_to 'Load to Google',google_user_path(id: @user, start_date: (Date.today.beginning_of_week(start_day = :sunday)-7).strftime("%m/%d/%Y"),end_date: (Date.today.end_of_week(start_day = :sunday)-7).strftime("%m/%d/%Y")), class: 'btn btn-default' %>
<% end %> <!-- hide until I can work out logging into google -->
</div>