config/routes.rb
Scheduling::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
	resources :users do
		member do
			get :google
		end
	end
	
	resources :sessions, only: [:new, :create, :destroy]
	resources :features do
	  member do 
	    get :toggle
	  end
	end
	get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy', via: :delete
	
	resources :schedules do
		collection do
			get :calendar
			get :addnew
		end
		member do
			get :rewrite
			get :calendar_update
			get :pop_up
		end
	end
  resources :projects do
		collection do
			get :autocomplete
		end
	end
	resources :static_pages do
		member do
			get :rewrite
		end
	end
	root to: "static_pages#home"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header" id="navbar_logo">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="<%= root_path %>" class="navbar-brand">Time Saver</a>
    </div>
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <!-- Collect the nav links, forms, and other content for toggling -->
	<% if signed_in? %>
		<% if current_page?(root_path) %>
			<%= render "layouts/start_bar", remote:true %>
		<% else %>
			<%= render "layouts/start_bar", remote:false %>
		<% end %>
	<% end %>

      <ul class="nav navbar-nav navbar-right" id="navbar_links">

				<% if user_signed_in? %>
					<li><a href="#">Logged in as <strong><%= current_user.name %></strong></a></li>
					<li><%= link_to "Edit Schedule", schedules_path %></li>
					<li><%= link_to "Calendar", calendar_schedules_path %></li>
					<li><%= link_to "Time Spent", user_path(current_user) %></li>
					<li><a href="#" class="dropdown-toggle" data-toggle="dropdown">
						Account <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						  <li><%= link_to "Projects", projects_path %></li>
						  <% if current_user.admin? %>
						  <li><%= link_to "Users", users_path %></li>
						  <% end %>
						  <li><a href="#" data-toggle="modal" data-target="#Settings">Settings</a></li>
						  <li><a href="#" data-toggle="modal" data-target="#Password">Update Password</a></li>
						  <!--<li><a href="#" data-toggle="modal" data-target="#Settings">Settings</a></li>-->
						  <li class="divider"></li>
						  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
						  <!--<li><%= link_to "Sign out", signout_path %></li>-->
					</ul></li>

				<% end %>
			</ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<% if user_signed_in? %>
<div class="modal fade" id="Settings" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="width:400px">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="SettingsLabel">Settings</h4>
      </div>
			<div class="modal-body">
				<%= form_for current_user, role: 'form', html: {class: "form-horizontal"} do |f| %>
					<div class="form-group">
						<label for="user_name" class="col-sm-4 control-label">Name</label>
						<div class="col-sm-8">
							<%= f.text_field :name, type: "name", class: "form-control" %>
						</div>
					</div>
					<div class="form-group">
						<label for="user_email" class="col-sm-4 control-label">Email</label>
						<div class="col-sm-8">
							<%= f.text_field :email, type: "email", class: "form-control"  %></div>
						</div>
					<div class="form-group">
						<label for="user_time_zone" class="col-sm-4 control-label">Time Zone</label>
						<div class="col-sm-8">
							<%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, {}, {class: "form-control"} %>
						</div>
					</div>
					<% if f.object.encrypted_password.present? %>
						<div class="form-group">
							<label for="user_password" class="col-sm-4 control-label">Password</label>
							<div class="col-sm-8">
								<%= f.password_field :password, type: "password", class: "form-control"  %>
							</div>
						</div>
						<div class="form-group">
							<label for="user_password_confirmation" class="col-sm-4 control-label">Password Confirmation</label>
							<div class="col-sm-8">
								<%= f.password_field :password_confirmation, type: "password", class: "form-control"  %>
							</div>
						</div>
					<% end %>
				</div>
				<div class="modal-footer">
					<%= f.submit "Save changes", class: "btn btn-default" %>
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			<% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="Password" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="SettingsLabel">Update Password</h4></div>
                <div class="modal-body" style="text-align:center">

<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { class: "form-horizontal", method: :put }) do |f| %>
<%= devise_error_messages! %>

<%= f.hidden_field :reset_password_token %>

<div class="form-group">
			<label for="user_password" class="col-sm-6 control-label">New Password</label>
			<div class="col-sm-6">
<%= f.password_field :password, autofocus: true, autocomplete: "off", class: "form-control" %></div>
</div>
<div class="form-group">
			<label for="user_password_confirmation" class="col-sm-6 control-label">Confirm</label>
						<div class="col-sm-6">
<%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %></div>
</div>
<div class="modal-footer">

<%= f.submit "Save changes", class: "btn btn-default" %>
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
<% end %>
</div>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_start_bar.html.erb
<%= form_tag(new_schedule_path, class: "navbar-form navbar-left", id: "go_form", method: :get, remote: remote) do %>
	<div class="form-group" id="text_name">
		<%= text_field_tag :name, "", data: {autocomplete_source: autocomplete_projects_path}, placeholder: "Project", class: "form-control autocomplete-project" %>
	</div>
	<div class="checkbox navbar-btn">
		<label class="navbar-link" >
			<%= check_box_tag "now", true, name: "now" %>
			Start Now
		</label>
	</div>
	<div class="form-group" id="now-text-field" style="display:none">
		<%= text_field_tag :start_at, Time.zone.now.strftime("%m/%d/%Y %I:%M %p"), class: "form-control datetimepicker", id: "main_start_at", style: "display:inline;width:165px" %>
	</div>
	<button class="btn btn-default" name="go" type="submit" id="main-play">
		<span class="glyphicon glyphicon-play"></span>
	</button>
	<span id="stopbutton">
		<%= render "static_pages/stop_button" %>
	</span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title ? @title : "Time Saver" %></title>
  <%= stylesheet_link_tag "application", media: "all","data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <link rel="apple-touch-icon" href="<%= image_path 'iTunesArtwork@2x.png' %>" />
  <meta name="viewport" content="width=device-width; initial-scale=1.0;" />
</head>
<body>
<%= render "layouts/navbar" %>
<div class="container container-fluid">

<%= yield %>

<% if signed_in? %>
  <%= content_tag "div", id: "hours_popup", data: {day: Schedule.total_time("day",current_user), week: Schedule.total_time("week",current_user), working: current_user.working?}, class: "hidden1 btn btn-default" do %>
  <h3 style="margin-top:5px;">Hours</h3>
  <div id="hours" style="display:none">Today: <span id="hours_day"><%= (Schedule.total_time("day",current_user)/3600).round(2) %></span><br>
    				This Week:<span id="hours_week"><%= (Schedule.total_time("week",current_user)/3600).round(2) %></span>
   </div>
  <% end %>

<% end %>
</div>
</body>
</html>